apiVersion: apps/v1
kind: Deployment
metadata: 
   name: project-app
   labels:
       app: project

spec:
   replica: 3
   selector:
        matchLabels:
            app: project
   template:
     metadata:
        labels:
           app: project 

    spec:
      containers:
      - name: project
        image: chandana1213/webapp
        ports:
        - containerPort: 8000
