apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
  labels:
    app: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: project
        image: chandana1213/webapp
        ports:
        - containerPort: 8000
